### ISSUE TITLE
支持预签名上传

### ISSUE THREAD

**Issue by xiucaiwu** [duxweb/go-storage#2]
各大云存储都支持预签名上传,后端返回一个认证token,前端拿到token调用对应服务商的SDK直接把文件上传到云存储,省去了先传到服务端服务端在传到云存储的一道中间过程

**Comment by dux-web** [comment]
好的，计划开发中

**Comment by kenny-yao** [comment]
> 好的，计划开发中

加油

**Comment by dux-web** [comment]
使用最新V2版本
